model_versions: "v1.0.0"
choosen_method: "Random Forest"
methods:
  - name: "Logistic Regression"
    config:
      max_iter: 1000
  - name: "Random Forest"
    config:
      n_estimators: 100
      max_depth: null
  - name: "SVM"
    config:
      C: 1.0
      kernel: "rbf"